### ISSUE TITLE
Item names and recipies are not displaying correctly 1.10.2

### ISSUE THREAD

**Issue by xevidos** [Mordenkainen/EquivalentEnergistics#91]
Hello,

On 1.10.2 the names of your items are tile.xxx then the coded name of the item instead of the display name.  Also in NEI the recipes do not show.  I have attached three screenshots to show what I mean.
![screen shot 2018-03-09 at 10 31 02 pm](https://user-images.githubusercontent.com/13248960/37237950-da9a0a70-23e9-11e8-9de2-8bcec87b1b33.png)
![screen shot 2018-03-09 at 10 31 05 pm](https://user-images.githubusercontent.com/13248960/37237951-daa7e9ce-23e9-11e8-9b78-58e94bce471e.png)
![screen shot 2018-03-09 at 10 31 07 pm](https://user-images.githubusercontent.com/13248960/37237952-dab519e6-23e9-11e8-9d2d-c937981db20f.png)

**Comment by Mordenkainen** [comment]
Thanks for reporting it. I'll take a look.

**Comment by xevidos** [comment]
I apologize I forgot to give my versions of Project E and Applied Energistics.

appliedenergistics2-rv4-stable-1
ProjectE-1.10.2-PE1.3.1

**Comment by Mordenkainen** [comment]
I should have new versions out this weekend to address this. Thanks again for reporting it.

**Comment by xevidos** [comment]
Sounds good, I am excited for the release!  Thank you for your hard work!

**Comment by basdedraak** [comment]
have you updated yet because this is still a problem
using V 1.10.2-0.8

**Comment by Mordenkainen** [comment]
I have not. RL has not left me much time lately, hence why the issue is still in an "open" state.

**Comment by Mordenkainen** [comment]
Fixed

**Comment by xevidos** [comment]
Hello,

For some reason I am still experiencing this issue.  I can now see the recipes but not the names of the objects.

Both the server and the client have 0.8.1 for 1.10.2

**Comment by xevidos** [comment]
![screen shot 2018-04-17 at 6 34 40 pm](https://user-images.githubusercontent.com/13248960/38902453-8f6695de-426e-11e8-99af-bc8e8733b680.png)
